"use client";

import { ChangeEvent, DragEvent, useEffect, useMemo, useRef, useState } from "react";
import jsQR from "jsqr";
import QRCode from "qrcode";

type Tool = { id: string; name: string; desc: string; icon: string; cat: string; tags: string };
const TOOLS: Tool[] = [
  ["scan","Scanner QR","Caméra ou image, résultat instantané","⌗","QR & codes","qr caméra décoder"],
  ["create","Créer un QR","Lien, Wi-Fi, contact, événement et paiement","▦","QR & codes","générer wifi vcard sms email epc"],
  ["barcode","Code-barres","Lire un produit et comparer son prix","▥","QR & codes","ean produit prix"],
  ["batch","QR en lot","Créer plusieurs QR depuis une liste","⊞","QR & codes","csv liste plusieurs"],
  ["history","Historique local","Retrouver tes derniers scans","◴","QR & codes","favoris récent"],
  ["url","Analyseur de lien","Repérer les liens potentiellement suspects","⌁","Sécurité","phishing url domaine"],
  ["password","Mot de passe","Générateur robuste et personnalisable","✳","Sécurité","password aléatoire"],
  ["hash","Empreinte SHA-256","Vérifier un texte ou un fichier","#","Sécurité","hash checksum fichier"],
  ["cipher","Coffre de texte","Chiffrer et déchiffrer localement","◇","Sécurité","aes cryptage"],
  ["image","Convertir une image","Compresser, redimensionner et convertir","◫","Images","jpg png webp métadonnées"],
  ["color","Couleur d’une image","Prélever une couleur et copier son code","◉","Images","palette pipette hex"],
  ["favicon","Créateur de favicon","Transformer une image en icône","◆","Images","icone site"],
  ["signature","Signature","Signer à la main et exporter en PNG","〽","Images","dessin signature"],
  ["json","Outil JSON","Formater, réduire et valider","{ }","Développeur","pretty minify"],
  ["codec","Encodeur universel","Base64, URL et lecture de JWT","↔","Développeur","encode decode"],
  ["uuid","Générateur UUID","Créer des identifiants uniques","✣","Développeur","guid"],
  ["timestamp","Horodatage Unix","Convertir une date et un timestamp","◷","Développeur","epoch temps"],
  ["units","Convertisseur","Longueur, poids et température","⇄","Calculs","unités kg km"],
  ["split","Partager l’addition","Pourboire et montant par personne","÷","Calculs","restaurant"],
  ["timer","Minuteur","Compte à rebours simple et précis","◒","Calculs","chronomètre"],
  ["document","Scanner document","Nettoyer une photo et l’exporter","▤","Documents","scan papier contraste"],
  ["ocr","Extraire le texte","Reconnaissance de texte depuis une photo","Aa","Documents","ocr photo texte"],
  ["inventory","Mode inventaire","Enregistrer des produits et exporter en CSV","▥","Pro","stock produits csv"],
  ["invoice","Créateur de facture","Préparer et imprimer une facture simple","€","Pro","facture client"],
  ["iban","Vérifier un IBAN","Contrôler rapidement un numéro bancaire","BE","Pro","banque paiement"],
  ["vat","Calculateur TVA","Passer du prix HT au prix TTC","%","Calculs","taxe ht ttc"],
  ["whatsapp","Lien WhatsApp","Créer un lien avec message prérempli","◖","Partage","message téléphone"],
  ["voice","Dictée vocale","Transformer la voix en texte","●","Partage","micro parole transcription"],
  ["backup","Sauvegarde locale","Exporter ou restaurer les données Qrio","⇩","Sécurité","backup restaurer"],
  ["currency","Devises","Convertir avec ton taux du jour","¤","Calculs","euro dollar change"],
].map(([id,name,desc,icon,cat,tags])=>({id,name,desc,icon,cat,tags}));
const CATS=["Tous","QR & codes","Sécurité","Images","Documents","Pro","Partage","Développeur","Calculs"];

function Panel({title,desc,children}:{title:string;desc:string;children:React.ReactNode}) {
  return <section className="panel"><header><small>OUTIL LOCAL</small><h2>{title}</h2><p>{desc}</p></header>{children}</section>;
}
const save=(url:string,name:string)=>{const a=document.createElement("a");a.href=url;a.download=name;a.click()};
const b64=(v:Uint8Array)=>{let s="";v.forEach(x=>s+=String.fromCharCode(x));return btoa(s)};
const unb64=(v:string)=>Uint8Array.from(atob(v),x=>x.charCodeAt(0));

export default function Home(){
  const [active,setActive]=useState("scan"),[cat,setCat]=useState("Tous"),[query,setQuery]=useState("");
  const [favorites,setFavorites]=useState<string[]>([]),[history,setHistory]=useState<string[]>([]);
  const [recent,setRecent]=useState<string[]>([]),[dark,setDark]=useState(false),[installPrompt,setInstallPrompt]=useState<Event|null>(null);
  useEffect(()=>{
    setFavorites(JSON.parse(localStorage.getItem("qrio-favorites")||"[]"));setHistory(JSON.parse(localStorage.getItem("qrio-history")||"[]"));setRecent(JSON.parse(localStorage.getItem("qrio-recent-tools")||"[]"));
    const requested=new URLSearchParams(location.search).get("outil");if(requested&&TOOLS.some(t=>t.id===requested))setActive(requested);
    const saved=localStorage.getItem("qrio-theme"),isDark=saved==="dark"||(!saved&&matchMedia("(prefers-color-scheme: dark)").matches);setDark(isDark);document.documentElement.dataset.theme=isDark?"dark":"light";
    if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js");
    const capture=(e:Event)=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener("beforeinstallprompt",capture);return()=>window.removeEventListener("beforeinstallprompt",capture);
  },[]);
  const filtered=useMemo(()=>TOOLS.filter(t=>(cat==="Tous"||t.cat===cat)&&`${t.name} ${t.desc} ${t.tags}`.toLowerCase().includes(query.toLowerCase())),[cat,query]);
  const favorite=(id:string)=>{const n=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(n);localStorage.setItem("qrio-favorites",JSON.stringify(n))};
  const remember=(v:string)=>{const n=[v,...history.filter(x=>x!==v)].slice(0,30);setHistory(n);localStorage.setItem("qrio-history",JSON.stringify(n))};
  const openTool=(id:string)=>{setActive(id);const n=[id,...recent.filter(x=>x!==id)].slice(0,4);setRecent(n);localStorage.setItem("qrio-recent-tools",JSON.stringify(n));setTimeout(()=>document.querySelector(".activeTool")?.scrollIntoView({behavior:"smooth"}),20)};
  const toggleTheme=()=>{const n=!dark;setDark(n);document.documentElement.dataset.theme=n?"dark":"light";localStorage.setItem("qrio-theme",n?"dark":"light")};
  const install=async()=>{if(installPrompt){await (installPrompt as Event&{prompt:()=>Promise<void>}).prompt();setInstallPrompt(null)}else alert("Sur iPhone : touche Partager puis « Sur l’écran d’accueil ». Sur Android : ouvre le menu puis « Installer l’application ».")};
  return <main>
    <nav><a className="brand" href="#"><i>▦</i>Qrio</a><div><button className="navAction" onClick={toggleTheme} aria-label="Changer le thème">{dark?"☀":"☾"}</button><button className="install" onClick={install}>Installer</button><a href="#tools">Outils</a><span>● Local & privé</span></div></nav>
    <section className="hero"><small>✦ TA BOÎTE À OUTILS NUMÉRIQUE</small><h1>Un outil pour chaque<br/><em>petit problème.</em></h1><p>QR codes, documents, sécurité, images, outils professionnels et calculs rapides. Gratuit, sans compte et directement dans ton navigateur.</p><div><b>{TOOLS.length}</b> outils <b>Hors ligne</b> disponible <b>100%</b> privé</div><button className="heroInstall" onClick={install}>＋ Installer Qrio sur mon téléphone</button></section>
    {recent.length>0&&<section className="recent"><small>UTILISÉS RÉCEMMENT</small><div>{recent.map(id=>{const t=TOOLS.find(x=>x.id===id);return t&&<button key={id} onClick={()=>openTool(id)}><i>{t.icon}</i><span>{t.name}</span></button>})}</div></section>}
    <section className="toolbox" id="tools">
      <aside><label>⌕ <input aria-label="Rechercher" placeholder="Rechercher un outil…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{CATS.map(c=><button className={cat===c?"on":""} key={c} onClick={()=>setCat(c)}>{c}<small>{c==="Tous"?TOOLS.length:TOOLS.filter(t=>t.cat===c).length}</small></button>)}</aside>
      <div className="content"><div className="grid">{filtered.map(t=><article key={t.id} className={active===t.id?"selected":""} onClick={()=>openTool(t.id)}><button className="star" aria-label={`Ajouter ${t.name} aux favoris`} onClick={e=>{e.stopPropagation();favorite(t.id)}}>{favorites.includes(t.id)?"★":"☆"}</button><i>{t.icon}</i><small>{t.cat}</small><h3>{t.name}</h3><p>{t.desc}</p><b>Ouvrir →</b></article>)}</div>
        <div className="activeTool">
          {active==="scan"&&<Scanner done={remember}/>} {active==="create"&&<Creator/>} {active==="batch"&&<Batch/>}
          {active==="barcode"&&<Barcode/>} {active==="history"&&<History items={history} clear={()=>{setHistory([]);localStorage.removeItem("qrio-history")}}/>}
          {active==="url"&&<UrlCheck/>} {active==="password"&&<Password/>} {active==="hash"&&<Hash/>} {active==="cipher"&&<Cipher/>}
          {["image","color","favicon"].includes(active)&&<ImageTool mode={active}/>} {active==="signature"&&<Signature/>}
          {active==="json"&&<JsonTool/>} {active==="codec"&&<Codec/>} {active==="uuid"&&<Uuid/>} {active==="timestamp"&&<Timestamp/>}
          {active==="units"&&<Units/>} {active==="split"&&<Split/>} {active==="timer"&&<Timer/>}
          {active==="document"&&<DocumentTool/>} {active==="ocr"&&<OcrTool/>} {active==="inventory"&&<Inventory/>}
          {active==="invoice"&&<Invoice/>} {active==="iban"&&<Iban/>} {active==="vat"&&<Vat/>}
          {active==="whatsapp"&&<Whatsapp/>} {active==="voice"&&<Voice/>} {active==="backup"&&<Backup/>} {active==="currency"&&<Currency/>}
        </div>
      </div>
    </section>
    <footer><b>Qrio Toolbox</b><span>Tout se passe sur ton appareil · Aucun compte · Aucune publicité</span></footer>
    <div className="bottomNav"><button className={active==="scan"?"on":""} onClick={()=>openTool("scan")}><i>⌗</i><span>Scanner</span></button><button className={active==="create"?"on":""} onClick={()=>openTool("create")}><i>▦</i><span>Créer</span></button><button onClick={()=>document.getElementById("tools")?.scrollIntoView({behavior:"smooth"})}><i>⊞</i><span>Outils</span></button><button className={active==="history"?"on":""} onClick={()=>openTool("history")}><i>◴</i><span>Récents</span></button></div>
  </main>
}

function Scanner({done}:{done:(v:string)=>void}){
  const [result,setResult]=useState(""),[status,setStatus]=useState("Prêt à scanner"),[live,setLive]=useState(false),[drag,setDrag]=useState(false),[torch,setTorch]=useState(false);
  const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),frame=useRef<number|null>(null),file=useRef<HTMLInputElement>(null);
  const stop=()=>{if(frame.current)cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop());setLive(false);setTorch(false)};
  useEffect(()=>()=>stop(),[]);
  const decode=(c:HTMLCanvasElement)=>{const x=c.getContext("2d",{willReadFrequently:true});if(!x)return false;const im=x.getImageData(0,0,c.width,c.height),code=jsQR(im.data,im.width,im.height,{inversionAttempts:"attemptBoth"});if(!code)return false;setResult(code.data);done(code.data);setStatus("QR décodé");navigator.vibrate?.(120);stop();return true};
  const loop=()=>{const v=video.current;if(!v||v.readyState<2){frame.current=requestAnimationFrame(loop);return}const c=document.createElement("canvas");c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d")?.drawImage(v,0,0);if(!decode(c))frame.current=requestAnimationFrame(loop)};
  const start=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}});stream.current=s;setLive(true);setStatus("Place le QR dans le cadre");requestAnimationFrame(()=>{if(video.current){video.current.srcObject=s;video.current.play().then(loop)}})}catch{setStatus("Caméra indisponible — utilise une image")}};
  const toggleTorch=async()=>{const track=stream.current?.getVideoTracks()[0];if(!track)return;try{const next=!torch;await track.applyConstraints({advanced:[{torch:next} as MediaTrackConstraintSet]});setTorch(next)}catch{setStatus("Lampe torche non disponible")}};
  const share=async()=>{if(navigator.share)await navigator.share({title:"Résultat Qrio",text:result});else await navigator.clipboard.writeText(result)};
  const read=(f?:File)=>{if(!f?.type.startsWith("image/"))return;const im=new Image();im.onload=()=>{const c=document.createElement("canvas"),s=Math.min(1,1800/Math.max(im.width,im.height));c.width=im.width*s;c.height=im.height*s;c.getContext("2d")?.drawImage(im,0,0,c.width,c.height);if(!decode(c))setStatus("Aucun QR trouvé");URL.revokeObjectURL(im.src)};im.src=URL.createObjectURL(f);setStatus("Analyse…")};
  return <Panel title="Scanner un QR code" desc="Caméra plein écran ou galerie. Rien ne quitte ton appareil."><div className="cols"><div><div className={`camera ${live?"live":""}`}><video ref={video} muted playsInline/><span>⌗</span>{!live?<button onClick={start}>Activer la caméra</button>:<div className="cameraActions"><button onClick={toggleTorch}>{torch?"Éteindre":"Lampe"}</button><button onClick={stop}>Fermer</button></div>}</div><button className={drag?"drop drag":"drop"} onClick={()=>file.current?.click()} onDragOver={(e:DragEvent)=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={(e:DragEvent)=>{e.preventDefault();setDrag(false);read(e.dataTransfer.files[0])}}>▧ Choisir une image dans la galerie</button><input hidden ref={file} type="file" accept="image/*" onChange={(e:ChangeEvent<HTMLInputElement>)=>read(e.target.files?.[0])}/><p className="hint">{status}</p></div><div className="result">{result?<><label>CONTENU DÉCODÉ</label><pre>{result}</pre><div className="buttons"><button onClick={()=>navigator.clipboard.writeText(result)}>Copier</button><button onClick={share}>Partager</button>{/^https?:\/\//i.test(result)&&<a href={result} target="_blank">Ouvrir ↗</a>}</div></>:<div className="empty"><b>⌗</b><strong>En attente d’un QR</strong></div>}</div></div></Panel>
}

function Creator(){
  const presets:Record<string,string>={Lien:"https://","Wi-Fi":"WIFI:T:WPA;S:NomDuWifi;P:MotDePasse;;",Contact:"BEGIN:VCARD\nVERSION:3.0\nFN:Prénom Nom\nTEL:+32\nEMAIL:bonjour@exemple.com\nEND:VCARD","E-mail":"mailto:bonjour@exemple.com?subject=Bonjour",SMS:"SMSTO:+32:Bonjour",Événement:"BEGIN:VEVENT\nSUMMARY:Mon événement\nDTSTART:20260801T120000Z\nEND:VEVENT",Paiement:"BCD\n002\n1\nSCT\nBIC\nNOM\nBE00000000000000\nEUR10.00"};
  const [value,setValue]=useState("https://"),[qr,setQr]=useState("");
  return <Panel title="Créer un QR code" desc="Lien, Wi-Fi, contact, message, événement ou paiement EPC."><div className="cols"><div className="form"><div className="chips">{Object.entries(presets).map(([k,v])=><button key={k} onClick={()=>setValue(v)}>{k}</button>)}</div><textarea value={value} onChange={e=>setValue(e.target.value)}/><button className="primary" onClick={async()=>setQr(await QRCode.toDataURL(value,{width:900,margin:2,errorCorrectionLevel:"H"}))}>Générer le QR →</button></div><div className="result">{qr?<><img className="qr" src={qr} alt="QR généré"/><button onClick={()=>save(qr,"qrio-code.png")}>Télécharger PNG</button></>:<div className="empty"><b>▦</b><strong>Ton QR apparaîtra ici</strong></div>}</div></div></Panel>
}

function Batch(){const [text,setText]=useState("https://tgappstudio.com\nBonjour"),[items,setItems]=useState<{t:string;u:string}[]>([]);return <Panel title="QR en lot" desc="Une ligne égale un QR, jusqu’à 30 codes."><div className="form"><textarea value={text} onChange={e=>setText(e.target.value)}/><button className="primary" onClick={async()=>{const v=text.split("\n").filter(Boolean).slice(0,30);setItems(await Promise.all(v.map(async t=>({t,u:await QRCode.toDataURL(t,{width:500})}))))}}>Générer la série</button></div><div className="batch">{items.map((x,i)=><button key={i} onClick={()=>save(x.u,`qr-${i+1}.png`)}><img src={x.u} alt=""/><span>{x.t}</span></button>)}</div></Panel>}
function Barcode(){const [value,setValue]=useState(""),[msg,setMsg]=useState("Importe une image ou saisis le code.");const scan=async(f?:File)=>{try{if(!f)return;const D=(window as unknown as {BarcodeDetector:new(o:{formats:string[]})=>{detect:(b:ImageBitmap)=>Promise<{rawValue:string}[]>}}).BarcodeDetector;const r=await new D({formats:["ean_13","ean_8","upc_a","code_128"]}).detect(await createImageBitmap(f));if(r[0])setValue(r[0].rawValue);else setMsg("Aucun code trouvé")}catch{setMsg("Lecture automatique non disponible sur ce navigateur.")}};return <Panel title="Lecteur de code-barres" desc="Lis un produit puis compare rapidement les prix."><div className="form narrow"><input type="file" accept="image/*" onChange={e=>scan(e.target.files?.[0])}/><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Code EAN"/><p className="hint">{msg}</p><div className="buttons"><a target="_blank" href={`https://www.google.com/search?tbm=shop&q=${value}`}>Google Shopping</a><a target="_blank" href={`https://www.amazon.fr/s?k=${value}`}>Amazon</a></div></div></Panel>}
function History({items,clear}:{items:string[];clear:()=>void}){return <Panel title="Historique local" desc="Tes 30 derniers scans restent uniquement dans ce navigateur."><div className="listTop">{items.length} élément(s)<button onClick={clear}>Tout effacer</button></div><div className="history">{items.map((x,i)=><div key={i}><span>{x}</span><button onClick={()=>navigator.clipboard.writeText(x)}>Copier</button></div>)}</div></Panel>}
function UrlCheck(){const [v,setV]=useState("https://");const r=useMemo(()=>{try{const u=new URL(v),f=[];if(u.protocol!=="https:")f.push("Pas de HTTPS");if(/xn--/.test(u.hostname))f.push("Caractères internationaux encodés");if(/\d+\.\d+\.\d+\.\d+/.test(u.hostname))f.push("Adresse IP utilisée");if((u.hostname.match(/-/g)||[]).length>3)f.push("Beaucoup de tirets");return {host:u.hostname,f}}catch{return null}},[v]);return <Panel title="Analyseur de lien" desc="Contrôle rapide avant d’ouvrir une adresse inconnue."><div className="form narrow"><input value={v} onChange={e=>setV(e.target.value)}/>{r&&<div className={`audit ${r.f.length?"warn":"good"}`}><b>{r.f.length?"Prudence recommandée":"Aucun signal évident"}</b><span>Domaine : {r.host}</span>{r.f.map(x=><span key={x}>• {x}</span>)}</div>}</div></Panel>}
function Password(){const [len,setLen]=useState(20),[v,setV]=useState("");const make=()=>{const c="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*+-_",a=crypto.getRandomValues(new Uint32Array(len));setV(Array.from(a,x=>c[x%c.length]).join(""))};useEffect(make,[len]);return <Panel title="Générateur de mot de passe" desc="Aléatoire cryptographique, créé localement."><div className="form narrow"><div className="big">{v}<button onClick={()=>navigator.clipboard.writeText(v)}>Copier</button></div><label>LONGUEUR : {len}</label><input type="range" min="8" max="64" value={len} onChange={e=>setLen(+e.target.value)}/><button className="primary" onClick={make}>Nouveau mot de passe</button></div></Panel>}
function Hash(){const [v,setV]=useState(""),[out,setOut]=useState("");const run=async(b:ArrayBuffer)=>setOut(Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",b)),x=>x.toString(16).padStart(2,"0")).join(""));return <Panel title="Empreinte SHA-256" desc="Vérifie un texte ou un fichier sans l’envoyer."><div className="form"><textarea value={v} onChange={e=>setV(e.target.value)} placeholder="Texte…"/><input type="file" onChange={async e=>{const f=e.target.files?.[0];if(f)run(await f.arrayBuffer())}}/><button className="primary" onClick={()=>run(new TextEncoder().encode(v).buffer)}>Calculer</button>{out&&<pre>{out}</pre>}</div></Panel>}
function Cipher(){const [text,setText]=useState(""),[pass,setPass]=useState(""),[out,setOut]=useState("");const key=async(s:Uint8Array)=>crypto.subtle.deriveKey({name:"PBKDF2",salt:s as BufferSource,iterations:150000,hash:"SHA-256"},await crypto.subtle.importKey("raw",new TextEncoder().encode(pass),"PBKDF2",false,["deriveKey"]),{name:"AES-GCM",length:256},false,["encrypt","decrypt"]);const enc=async()=>{try{const s=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),d=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(s),new TextEncoder().encode(text)));setOut(`QRIO1.${b64(s)}.${b64(iv)}.${b64(d)}`)}catch{setOut("Erreur")}};const dec=async()=>{try{const [,s,iv,d]=text.split(".");setOut(new TextDecoder().decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(iv) as BufferSource},await key(unb64(s)),unb64(d) as BufferSource)))}catch{setOut("Mot de passe ou contenu incorrect.")}};return <Panel title="Coffre de texte" desc="Chiffrement AES-GCM protégé par ton mot de passe."><div className="form"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Texte ou contenu QRIO1…"/><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Mot de passe"/><div className="buttons"><button onClick={enc}>Chiffrer</button><button onClick={dec}>Déchiffrer</button></div>{out&&<pre>{out}</pre>}</div></Panel>}

function ImageTool({mode}:{mode:string}){const [img,setImg]=useState<HTMLImageElement|null>(null),[url,setUrl]=useState(""),[width,setWidth]=useState(1200),[quality,setQuality]=useState(.82),[format,setFormat]=useState("image/webp"),[color,setColor]=useState("#7057e8");const load=(f?:File)=>{if(!f)return;const i=new Image();i.onload=()=>{setImg(i);setUrl(i.src);setWidth(Math.min(1200,i.width))};i.src=URL.createObjectURL(f)};const render=(square=false)=>{if(!img)return;const c=document.createElement("canvas"),w=square?512:width,h=square?512:Math.round(img.height*w/img.width);c.width=w;c.height=h;const x=c.getContext("2d")!;if(square){const s=Math.min(img.width,img.height);x.drawImage(img,(img.width-s)/2,(img.height-s)/2,s,s,0,0,w,h)}else x.drawImage(img,0,0,w,h);save(c.toDataURL(square?"image/png":format,quality),square?"favicon.png":`image.${format.split("/")[1]}`)};const pick=(e:React.MouseEvent<HTMLImageElement>)=>{if(!img)return;const r=e.currentTarget.getBoundingClientRect(),c=document.createElement("canvas");c.width=img.width;c.height=img.height;const x=c.getContext("2d")!;x.drawImage(img,0,0);const p=x.getImageData((e.clientX-r.left)/r.width*img.width,(e.clientY-r.top)/r.height*img.height,1,1).data;setColor("#"+[p[0],p[1],p[2]].map(n=>n.toString(16).padStart(2,"0")).join(""))};return <Panel title={mode==="image"?"Convertir et compresser":mode==="color"?"Prélever une couleur":"Créer un favicon"} desc="L’image est traitée sur ton appareil et ses métadonnées sont supprimées."><div className="cols"><div className="form"><input type="file" accept="image/*" onChange={e=>load(e.target.files?.[0])}/>{mode==="image"&&<><label>LARGEUR : {width}px</label><input type="range" min="128" max="2400" value={width} onChange={e=>setWidth(+e.target.value)}/><label>QUALITÉ : {Math.round(quality*100)}%</label><input type="range" min=".2" max="1" step=".05" value={quality} onChange={e=>setQuality(+e.target.value)}/><select value={format} onChange={e=>setFormat(e.target.value)}><option value="image/webp">WebP</option><option value="image/jpeg">JPG</option><option value="image/png">PNG</option></select><button className="primary" onClick={()=>render()}>Convertir</button></>}{mode==="favicon"&&<button className="primary" onClick={()=>render(true)}>Créer l’icône 512 × 512</button>}{mode==="color"&&<><div className="color" style={{background:color}}>{color}</div><button onClick={()=>navigator.clipboard.writeText(color)}>Copier</button></>}</div><div className="result">{url?<img className="preview" src={url} alt="Aperçu" onClick={pick}/>:<div className="empty"><b>◫</b><strong>Choisis une image</strong></div>}</div></div></Panel>}
function Signature(){const ref=useRef<HTMLCanvasElement>(null),draw=useRef(false);const p=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*900/r.width,y:(e.clientY-r.top)*300/r.height}};return <Panel title="Signature manuscrite" desc="Dessine au doigt, à la souris ou au stylet."><canvas ref={ref} width="900" height="300" onPointerDown={e=>{draw.current=true;const x=ref.current!.getContext("2d")!,q=p(e);x.beginPath();x.moveTo(q.x,q.y)}} onPointerMove={e=>{if(!draw.current)return;const x=ref.current!.getContext("2d")!,q=p(e);x.lineWidth=5;x.lineCap="round";x.lineTo(q.x,q.y);x.stroke()}} onPointerUp={()=>draw.current=false}/><div className="buttons center"><button onClick={()=>ref.current?.getContext("2d")?.clearRect(0,0,900,300)}>Effacer</button><button onClick={()=>ref.current&&save(ref.current.toDataURL(),"signature.png")}>Télécharger PNG</button></div></Panel>}
function JsonTool(){const [v,setV]=useState('{"nom":"Qrio","prive":true}'),[s,setS]=useState("");const go=(min=false)=>{try{setV(JSON.stringify(JSON.parse(v),null,min?0:2));setS("JSON valide ✓")}catch(e){setS(`Erreur : ${(e as Error).message}`)}};return <Panel title="Outil JSON" desc="Formate, réduit et valide instantanément."><div className="form"><textarea value={v} onChange={e=>setV(e.target.value)}/><div className="buttons"><button onClick={()=>go()}>Formater</button><button onClick={()=>go(true)}>Réduire</button><button onClick={()=>navigator.clipboard.writeText(v)}>Copier</button></div><p className="hint">{s}</p></div></Panel>}
function Codec(){const [v,setV]=useState(""),[out,setOut]=useState(""),[mode,setMode]=useState("Base64");const enc=()=>{try{setOut(mode==="Base64"?btoa(unescape(encodeURIComponent(v))):encodeURIComponent(v))}catch{setOut("Format invalide")}};const dec=()=>{try{if(mode==="JWT"){const p=v.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");setOut(JSON.stringify(JSON.parse(decodeURIComponent(escape(atob(p)))),null,2))}else setOut(mode==="Base64"?decodeURIComponent(escape(atob(v))):decodeURIComponent(v))}catch{setOut("Format invalide")}};return <Panel title="Encodeur universel" desc="Base64, URL et lecture du contenu public d’un JWT."><div className="form"><div className="chips">{["Base64","URL","JWT"].map(x=><button key={x} onClick={()=>setMode(x)}>{x}</button>)}</div><textarea value={v} onChange={e=>setV(e.target.value)}/><div className="buttons">{mode!=="JWT"&&<button onClick={enc}>Encoder</button>}<button onClick={dec}>Décoder</button></div>{out&&<pre>{out}</pre>}</div></Panel>}
function Uuid(){const [n,setN]=useState(5),[out,setOut]=useState([crypto.randomUUID()]);return <Panel title="Générateur UUID v4" desc="Jusqu’à 25 identifiants uniques."><div className="form narrow"><input type="number" min="1" max="25" value={n} onChange={e=>setN(+e.target.value)}/><button className="primary" onClick={()=>setOut(Array.from({length:Math.min(25,n)},()=>crypto.randomUUID()))}>Générer</button><pre>{out.join("\n")}</pre><button onClick={()=>navigator.clipboard.writeText(out.join("\n"))}>Tout copier</button></div></Panel>}
function Timestamp(){const [t,setT]=useState(Math.floor(Date.now()/1000)),[d,setD]=useState(new Date().toISOString().slice(0,16));return <Panel title="Horodatage Unix" desc="Convertis une date en timestamp, et inversement."><div className="cols"><div className="form"><label>TIMESTAMP</label><input type="number" value={t} onChange={e=>setT(+e.target.value)}/><div className="big">{new Date(t*1000).toLocaleString("fr-BE")}</div></div><div className="form"><label>DATE</label><input type="datetime-local" value={d} onChange={e=>setD(e.target.value)}/><div className="big">{Math.floor(new Date(d).getTime()/1000)}</div></div></div></Panel>}
function Units(){const [kind,setKind]=useState("Longueur"),[v,setV]=useState(1);const out=kind==="Longueur"?`${v*1000} m · ${(v*.621371).toFixed(3)} mi`:kind==="Poids"?`${v*1000} g · ${(v*2.20462).toFixed(3)} lb`:`${(v*9/5+32).toFixed(1)} °F · ${(v+273.15).toFixed(1)} K`;return <Panel title="Convertisseur d’unités" desc="Longueur, poids et température."><div className="form narrow"><div className="chips">{["Longueur","Poids","Température"].map(x=><button key={x} onClick={()=>setKind(x)}>{x}</button>)}</div><input type="number" value={v} onChange={e=>setV(+e.target.value)}/><div className="big">{out}</div></div></Panel>}
function Split(){const [bill,setBill]=useState(80),[people,setPeople]=useState(2),[tip,setTip]=useState(10),total=bill*(1+tip/100);return <Panel title="Partager l’addition" desc="Pourboire et montant par personne."><div className="form narrow"><label>ADDITION (€)</label><input type="number" value={bill} onChange={e=>setBill(+e.target.value)}/><label>PERSONNES</label><input type="number" min="1" value={people} onChange={e=>setPeople(+e.target.value)}/><label>POURBOIRE : {tip}%</label><input type="range" min="0" max="30" value={tip} onChange={e=>setTip(+e.target.value)}/><div className="big">{(total/Math.max(1,people)).toFixed(2)} € / personne</div></div></Panel>}
function Timer(){const [s,setS]=useState(300),[run,setRun]=useState(false);useEffect(()=>{if(!run||s<=0)return;const id=setInterval(()=>setS(x=>x-1),1000);return()=>clearInterval(id)},[run,s]);return <Panel title="Minuteur" desc="Compte à rebours simple et précis."><div className="timer">{Math.floor(s/60).toString().padStart(2,"0")}:{(s%60).toString().padStart(2,"0")}</div><div className="buttons center"><button onClick={()=>setRun(!run)}>{run?"Pause":"Démarrer"}</button>{[300,600,1500].map(x=><button key={x} onClick={()=>{setRun(false);setS(x)}}>{x/60} min</button>)}</div></Panel>}

function DocumentTool(){const [src,setSrc]=useState(""),[contrast,setContrast]=useState(130),[gray,setGray]=useState(true);const process=(f?:File)=>{if(!f)return;const img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=img.width;c.height=img.height;const x=c.getContext("2d")!;x.filter=`${gray?"grayscale(1) ":""}contrast(${contrast}%) brightness(108%)`;x.drawImage(img,0,0);setSrc(c.toDataURL("image/jpeg",.9))};img.src=URL.createObjectURL(f)};return <Panel title="Scanner un document" desc="Améliore le contraste d’une photo de document et crée un JPG propre."><div className="cols"><div className="form"><input type="file" accept="image/*" capture="environment" onChange={e=>process(e.target.files?.[0])}/><label>CONTRASTE : {contrast}%</label><input type="range" min="80" max="200" value={contrast} onChange={e=>setContrast(+e.target.value)}/><label className="check"><input type="checkbox" checked={gray} onChange={e=>setGray(e.target.checked)}/> Noir et blanc</label><p className="hint">Reprends la photo après un changement de réglage.</p></div><div className="result">{src?<><img className="preview" src={src} alt="Document nettoyé"/><button onClick={()=>save(src,"document-qrio.jpg")}>Télécharger</button></>:<div className="empty"><b>▤</b><strong>Photographie ton document</strong></div>}</div></div></Panel>}

function OcrTool(){const [text,setText]=useState(""),[status,setStatus]=useState("La reconnaissance dépend des capacités de ton navigateur.");const run=async(f?:File)=>{if(!f)return;try{setStatus("Reconnaissance en cours…");const T=(window as unknown as {TextDetector?:new()=>{detect:(b:ImageBitmap)=>Promise<{rawValue:string}[]>}}).TextDetector;if(!T)throw new Error();const rows=await new T().detect(await createImageBitmap(f));setText(rows.map(r=>r.rawValue).join("\n"));setStatus(rows.length?"Texte extrait":"Aucun texte détecté")}catch{setStatus("OCR automatique indisponible ici. Essaie Chrome Android ou utilise le scanner de document.")}};return <Panel title="Extraire le texte d’une photo" desc="Reconnaissance locale lorsque le téléphone la prend en charge."><div className="form"><input type="file" accept="image/*" capture="environment" onChange={e=>run(e.target.files?.[0])}/><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Le texte apparaîtra ici…"/><div className="buttons"><button onClick={()=>navigator.clipboard.writeText(text)}>Copier</button><button onClick={()=>navigator.share?.({text})}>Partager</button></div><p className="hint">{status}</p></div></Panel>}

function Inventory(){type Row={code:string;name:string;qty:number};const [rows,setRows]=useState<Row[]>(()=>{try{return JSON.parse(localStorage.getItem("qrio-inventory")||"[]")}catch{return[]}}),[code,setCode]=useState(""),[name,setName]=useState("");const persist=(n:Row[])=>{setRows(n);localStorage.setItem("qrio-inventory",JSON.stringify(n))};const add=()=>{if(!code.trim())return;const found=rows.find(r=>r.code===code);persist(found?rows.map(r=>r.code===code?{...r,qty:r.qty+1}:r):[{code,name:name||"Produit",qty:1},...rows]);setCode("");setName("")};const csv=()=>{const content="Code,Produit,Quantité\n"+rows.map(r=>`\"${r.code}\",\"${r.name.replaceAll('"','""')}\",${r.qty}`).join("\n");save(URL.createObjectURL(new Blob([content],{type:"text/csv"})),"inventaire-qrio.csv")};return <Panel title="Mode inventaire" desc="Ajoute rapidement des références, compte les quantités et exporte en CSV."><div className="form narrow"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Code produit"/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom du produit"/><button className="primary" onClick={add}>Ajouter / compter +1</button><div className="inventory">{rows.map((r,i)=><div key={r.code}><span><b>{r.name}</b><small>{r.code}</small></span><input type="number" min="0" value={r.qty} onChange={e=>persist(rows.map((x,j)=>j===i?{...x,qty:+e.target.value}:x))}/></div>)}</div>{rows.length>0&&<div className="buttons"><button onClick={csv}>Exporter CSV</button><button onClick={()=>persist([])}>Vider</button></div>}</div></Panel>}

function Invoice(){const [seller,setSeller]=useState("TG App Studio"),[client,setClient]=useState("Client"),[item,setItem]=useState("Service"),[price,setPrice]=useState(100),[tax,setTax]=useState(21),total=price*(1+tax/100);return <Panel title="Créateur de facture" desc="Prépare une facture simple puis utilise l’impression du téléphone pour l’enregistrer en PDF."><div className="form invoice"><label>ÉMETTEUR</label><input value={seller} onChange={e=>setSeller(e.target.value)}/><label>CLIENT</label><input value={client} onChange={e=>setClient(e.target.value)}/><label>DESCRIPTION</label><input value={item} onChange={e=>setItem(e.target.value)}/><div className="inline"><input type="number" value={price} onChange={e=>setPrice(+e.target.value)} placeholder="Prix HT"/><input type="number" value={tax} onChange={e=>setTax(+e.target.value)} placeholder="TVA %"/></div><div className="invoicePreview"><small>FACTURE · {new Date().toLocaleDateString("fr-BE")}</small><h3>{seller}</h3><p>Facturé à : <b>{client}</b></p><hr/><p>{item}<b>{price.toFixed(2)} € HT</b></p><p>TVA {tax}%<b>{(total-price).toFixed(2)} €</b></p><h2>Total {total.toFixed(2)} €</h2></div><button className="primary" onClick={()=>window.print()}>Imprimer / Enregistrer en PDF</button></div></Panel>}

function Iban(){const [v,setV]=useState("BE");const clean=v.replace(/\s/g,"").toUpperCase();const valid=useMemo(()=>{if(!/^[A-Z]{2}\d{2}[A-Z0-9]{11,30}$/.test(clean))return false;const moved=clean.slice(4)+clean.slice(0,4),digits=moved.replace(/[A-Z]/g,c=>(c.charCodeAt(0)-55).toString());let rem=0;for(const d of digits)rem=(rem*10+ +d)%97;return rem===1},[clean]);return <Panel title="Vérifier un IBAN" desc="Contrôle mathématique du format. Cela ne confirme pas l’existence du compte."><div className="form narrow"><input value={v} onChange={e=>setV(e.target.value)} placeholder="BE00 0000 0000 0000"/><div className={`audit ${valid?"good":"warn"}`}><b>{valid?"IBAN mathématiquement valide ✓":"IBAN incomplet ou invalide"}</b><span>{clean.replace(/(.{4})/g,"$1 ").trim()}</span></div></div></Panel>}

function Vat(){const [net,setNet]=useState(100),[rate,setRate]=useState(21),gross=net*(1+rate/100);return <Panel title="Calculateur de TVA" desc="Calcule automatiquement la TVA et le prix toutes taxes comprises."><div className="form narrow"><label>PRIX HT</label><input type="number" value={net} onChange={e=>setNet(+e.target.value)}/><div className="chips">{[0,6,12,21].map(x=><button key={x} onClick={()=>setRate(x)}>{x}%</button>)}</div><label>TAUX : {rate}%</label><div className="big">{gross.toFixed(2)} € TTC</div><p className="hint">TVA : {(gross-net).toFixed(2)} €</p></div></Panel>}

function Whatsapp(){const [phone,setPhone]=useState("+32"),[message,setMessage]=useState("Bonjour !");const url=`https://wa.me/${phone.replace(/\D/g,"")}?text=${encodeURIComponent(message)}`;return <Panel title="Créer un lien WhatsApp" desc="Prépare un message qui s’ouvrira directement dans WhatsApp."><div className="form narrow"><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+32…"/><textarea value={message} onChange={e=>setMessage(e.target.value)}/><div className="buttons"><a href={url} target="_blank">Ouvrir WhatsApp</a><button onClick={()=>navigator.clipboard.writeText(url)}>Copier le lien</button><button onClick={()=>navigator.share?.({url})}>Partager</button></div></div></Panel>}

function Voice(){const [text,setText]=useState(""),[status,setStatus]=useState("Appuie pour commencer.");const listen=()=>{const W=window as unknown as {webkitSpeechRecognition?:new()=>{lang:string;continuous:boolean;interimResults:boolean;onresult:(e:{results:{length:number;[k:number]:{0:{transcript:string}}}})=>void;onerror:()=>void;onend:()=>void;start:()=>void}};if(!W.webkitSpeechRecognition){setStatus("Dictée non disponible dans ce navigateur.");return}const r=new W.webkitSpeechRecognition();r.lang="fr-FR";r.continuous=true;r.interimResults=false;r.onresult=e=>{let s="";for(let i=0;i<e.results.length;i++)s+=e.results[i][0].transcript+" ";setText(t=>t+s)};r.onerror=()=>setStatus("Le microphone n’est pas disponible.");r.onend=()=>setStatus("Dictée terminée.");r.start();setStatus("J’écoute…")};return <Panel title="Dictée vocale" desc="Transforme ta voix en texte avec la reconnaissance du navigateur."><div className="form"><button className="primary" onClick={listen}>● Commencer la dictée</button><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Le texte dicté apparaîtra ici…"/><div className="buttons"><button onClick={()=>navigator.clipboard.writeText(text)}>Copier</button><button onClick={()=>navigator.share?.({text})}>Partager</button></div><p className="hint">{status}</p></div></Panel>}

function Backup(){const input=useRef<HTMLInputElement>(null);const exportData=()=>{const data:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith("qrio-"))data[k]=localStorage.getItem(k)||""}save(URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),"sauvegarde-qrio.json")};const restore=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result));Object.entries(d).forEach(([k,v])=>{if(k.startsWith("qrio-")&&typeof v==="string")localStorage.setItem(k,v)});alert("Sauvegarde restaurée. Recharge la page.")}catch{alert("Fichier de sauvegarde invalide.")}};r.readAsText(f)};return <Panel title="Sauvegarde locale" desc="Transfère favoris, historique et inventaire vers un autre appareil."><div className="form narrow"><button className="primary" onClick={exportData}>Exporter ma sauvegarde</button><button onClick={()=>input.current?.click()}>Restaurer une sauvegarde</button><input hidden ref={input} type="file" accept=".json" onChange={e=>restore(e.target.files?.[0])}/><p className="hint">Le fichier ne contient que les données Qrio enregistrées sur cet appareil.</p></div></Panel>}

function Currency(){const [amount,setAmount]=useState(100),[rate,setRate]=useState(1.08);return <Panel title="Convertisseur de devises" desc="Entre le taux affiché par ta banque pour obtenir un calcul précis."><div className="form narrow"><label>MONTANT DE DÉPART</label><input type="number" value={amount} onChange={e=>setAmount(+e.target.value)}/><label>TAUX DE CONVERSION</label><input type="number" step=".0001" value={rate} onChange={e=>setRate(+e.target.value)}/><div className="big">{(amount*rate).toFixed(2)}</div><button onClick={()=>{setAmount(amount*rate);setRate(1/rate)}}>Inverser le calcul</button></div></Panel>}
